apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: c3pool-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: c3pool-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
