apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # 名字必须与下面的spec字段匹配, 并且格式为'<名称的复数形式>.<组名>'
  name: forecasttasks.batch.nanto.io
spec:
  # 组名称, 用于REST API: /apis/<组>/<版本>
  group: batch.nanto.io
  # 列举此 CustomResourceDefinition所支持的版本
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: ForecastWindow
          type: integer
          description: ForecastWindow description
          jsonPath: .spec.forecastWindow
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                scaleTargetRefs:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                    required:
                    - apiVersion
                    - kind
                    - name
                forecastWindow:
                  type: integer
                  minimum: 1
                  maximum: 1000
              required:
              - scaleTargetRefs
              - forecastWindow
  # 可以是Namespaced或Cluster
  scope: Namespaced
  names:
    # 名称的复数形式, 用于 URL: /apis/<组>/<版本>/<名称的复数形式>
    plural: forecasttasks
    # 名称的单数形式, 作为命令行使用时和显示时的别名
    singular: forecasttask
    # kind通常是单数形式的驼峰编码(PascalCased)形式, 在资源清单中会使用这一形式
    kind: ForecastTask
    # shortNames 允许在命令行使用较短的字符串来匹配资源
    shortNames:
      - ft
