apiVersion: aacontroller.k8s.io/v1
kind: ResourceRecommendation
metadata:
  name: example-rr
spec:
  apiVersion: apps/v1
  kind: Deployment
  resources:
    - name: deployment1
      placements:
        - flavorName: c6s.4xlarge.2
          amount: 50
        - flavorName: c3.4xlarge.2
          amount: 50
    - name: deployment2
      placements:
        - flavorName: c6.4xlarge.2
          amount: 20
        - flavorName: c3.4xlarge.2
          amount: 50
