---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9 # replace it with your exactly <image_name:tags>
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-deployment-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: aacontroller.k8s.io/v1
kind: AppawareHorizontalPodAutoscaler
metadata:
  name: appawarehpa-sample
spec:
  scaleTargetRef:
    apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    name:  nginx-deployment-hpa
  # 扩缩模式, scalingUpOnly:只扩模式, scalingDownOnly:只缩模式, auto:扩缩模式, observer:观察模式
  scaleMode: auto
  # 预测未来10分钟所需的副本数, 单位为分钟
  forecastWindow: 10
#  支持 cronJobs
#  jobs:
#    - name: "scale-up"
#      # target is the minReplicas = max(aaHPA scale up replicas, current replicas)
#      schedule: "0 */1 * * * *"
#      targetSize: 3
#      runOnce: true
#    - name: "scale-down"
#      # target is the maxReplicas = min(aaHPA scale up replicas, current replicas)
#      schedule: "30 */1 * * * *"
#      targetSize: 1
