---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c3pool-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9 # replace it with your exactly <image_name:tags>
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    release: cceaddon-cce-hpa-controller
  name: customedhorizontalpodautoscalers.autoscaling.cce.io
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/customedhorizontalpodautoscalers.autoscaling.cce.io
spec:
  conversion:
    strategy: None
  group: autoscaling.cce.io
  names:
    kind: CustomedHorizontalPodAutoscaler
    listKind: CustomedHorizontalPodAutoscalerList
    plural: customedhorizontalpodautoscalers
    shortNames:
      - customedhpa
    singular: customedhorizontalpodautoscaler
  preserveUnknownFields: true
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: CustomedHorizontalPodAutoscaler is the Schema for the customedhorizontalpodautoscalers
            API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: CustomedHorizontalPodAutoscalerSpec defines the desired state
                of CustomedHorizontalPodAutoscaler
              properties:
                coolDownTime:
                  type: string
                maxReplicas:
                  exclusiveMinimum: true
                  format: int32
                  maximum: 2147483647
                  minimum: 0
                  type: integer
                minReplicas:
                  exclusiveMinimum: true
                  format: int32
                  maximum: 2147483647
                  minimum: 0
                  type: integer
                rules:
                  items:
                    properties:
                      actions:
                        description: actions to take when trigger is hit
                        items:
                          description: What to do When Triggers be triggered
                          properties:
                            metricRange:
                              description: When metrics' value is in this range, do
                                the action. Not avaliable when rule type = Cron
                              type: string
                            minIncrement:
                              description: The minimum increment when Unit is Percent
                              format: int32
                              maximum: 2147483647
                              minimum: 0
                              type: integer
                            operationType:
                              description: ScaleUp/ScaleDown/ScaleTo
                              enum:
                                - ScaleUp
                                - ScaleDown
                                - ScaleTo
                              type: string
                            operationUnit:
                              enum:
                                - Percent
                                - Task
                              type: string
                            operationValue:
                              format: int32
                              maximum: 2147483647
                              minimum: 0
                              type: integer
                          required:
                            - operationType
                            - operationUnit
                            - operationValue
                          type: object
                        minItems: 1
                        type: array
                      cronTrigger:
                        description: trigger based on cron schedule
                        properties:
                          schedule:
                            description: cron expression
                            type: string
                        required:
                          - schedule
                        type: object
                      disable:
                        description: whether to disable this rule
                        type: boolean
                      metricTrigger:
                        description: trigger based on metric MetricTrigger
                        properties:
                          hitThreshold:
                            description: how much time the metric hit expression
                            format: int32
                            type: integer
                          metricName:
                            description: 'metric name: support CPURatioToRequest/MemoryRatioToRequest'
                            type: string
                          metricOperation:
                            description: '">" or "<"'
                            type: string
                          metricValue:
                            description: threshold，min=0,max = maxInt32
                            type: number
                          periodSeconds:
                            description: only 60/300/900/3600 s
                            enum:
                              - 60
                              - 300
                              - 900
                              - 3600
                            format: int32
                            type: integer
                          statistic:
                            description: instantaneous/average
                            type: string
                        required:
                          - hitThreshold
                          - metricName
                          - metricOperation
                          - metricValue
                          - periodSeconds
                          - statistic
                        type: object
                      ruleName:
                        description: 'rule name :'
                        maxLength: 20
                        pattern: '[a-z0-9]+'
                        type: string
                      ruleType:
                        description: 'rule type : Metric/Cron'
                        enum:
                          - Metric
                          - Cron
                        type: string
                    required:
                      - actions
                      - disable
                      - ruleName
                      - ruleType
                    type: object
                  maxItems: 10
                  type: array
                scaleTargetRef:
                  description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                  required:
                    - apiVersion
                    - kind
                    - name
                  type: object
              required:
                - coolDownTime
                - maxReplicas
                - minReplicas
                - scaleTargetRef
              type: object
            status:
              description: CustomedHorizontalPodAutoscalerStatus defines the observed
                state of CustomedHorizontalPodAutoscaler
              properties:
                conditions:
                  description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                  items:
                    properties:
                      countAfterScale:
                        description: The number of deployment instances after this rule
                          executes.
                        format: int32
                        type: integer
                      countBeforeScale:
                        description: The number of deployment instances before this
                          rule executes.
                        format: int32
                        type: integer
                      lastProbeTime:
                        description: Last execution time for this rule.
                        format: date-time
                        type: string
                      message:
                        description: Human readable message indicating details about
                          last transition.
                        type: string
                      ruleName:
                        description: The name of this rule to uniquely identify a rule
                        type: string
                      scaleAction:
                        description: The action which this rule take
                        properties:
                          metricRange:
                            description: When metrics' value is in this range, do the
                              action. Not avaliable when rule type = Cron
                            type: string
                          minIncrement:
                            description: The minimum increment when Unit is Percent
                            format: int32
                            maximum: 2147483647
                            minimum: 0
                            type: integer
                          operationType:
                            description: ScaleUp/ScaleDown/ScaleTo
                            enum:
                              - ScaleUp
                              - ScaleDown
                              - ScaleTo
                            type: string
                          operationUnit:
                            enum:
                              - Percent
                              - Task
                            type: string
                          operationValue:
                            format: int32
                            maximum: 2147483647
                            minimum: 0
                            type: integer
                        required:
                          - operationType
                          - operationUnit
                          - operationValue
                        type: object
                      state:
                        description: The State of this rule
                        type: string
                    required:
                      - countAfterScale
                      - countBeforeScale
                      - ruleName
                      - state
                    type: object
                  type: array
              required:
                - conditions
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: CustomedHorizontalPodAutoscaler
    listKind: CustomedHorizontalPodAutoscalerList
    plural: customedhorizontalpodautoscalers
    shortNames:
      - customedhpa
    singular: customedhorizontalpodautoscaler
  conditions:
    - lastTransitionTime: "2021-10-22T06:48:32Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2021-10-22T06:48:32Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1alpha1
