apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-auto-scaling-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: application-auto-scaling-service
  replicas: 1
  template:
    metadata:
      labels:
        app: application-auto-scaling-service
    spec:
#      nodeName: myread1
      serviceAccountName: application-auto-scaling-service-sa
      containers:
        - name: application-auto-scaling-service-container
          image: swr.ap-southeast-1.myhuaweicloud.com/nanto/application-auto-scaling-service:v1
          imagePullPolicy: Always
          env:
            - name: ClusterId
              value: ""
            - name: ObsEndpoint
              value: "https://obs.cn-north-4.myhuaweicloud.com"
            - name: ObsBucketName
              value: "nanto-bucket"
            - name: ObsSourceFileTemplate
              value: "./resources/%s.txt"
            - name: ObsObjectKeyNodeIdsTemplate
              value: "transcode/aass/%s_nodeIds.txt"
            - name: ObsObjectKeyStrategiesTemplate
              value: "transcode/aass/%s_strategies.json"
            - name: SyncNodeIdsToOBSIntervalMinute
              value: "1"
