apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-auto-scaling-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: application-auto-scaling-service
  replicas: 1
  template:
    metadata:
      labels:
        app: application-auto-scaling-service
    spec:
      nodeName: myread1
      serviceAccountName: application-auto-scaling-service-sa
      containers:
        - name: application-auto-scaling-service-container
          image: golang:1.16-alpine3.12
          imagePullPolicy: IfNotPresent
          env:
            - name: "GOPROXY"
              value: "https://goproxy.cn"
          workingDir: "/app"
          command: ["go","run","main.go"]
          volumeMounts:
            - name: app
              mountPath: /app
            - name: gopath
              mountPath: /go
#          ports:
#            - containerPort: 80
      volumes:
        - name: app
          hostPath:
            path: /home/hadoop/develop/GoLandProjects/gopath/src/nanto.io/application-auto-scaling-service
        - name: gopath
          hostPath:
            path: /home/hadoop/develop/GoLandProjects/gopath
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: application-auto-scaling-service-svc
#  namespace: default
#spec:
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: 80
#      nodePort: 31180
#  selector:
#    app: application-auto-scaling-service

