# 镜像部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-auto-scaling-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: application-auto-scaling-service
  replicas: 1
  template:
    metadata:
      labels:
        app: application-auto-scaling-service
    spec:
      serviceAccountName: application-auto-scaling-service-sa
      containers:
      - name: application-auto-scaling-service-container
        image: swr.ap-southeast-1.myhuaweicloud.com/nanto/application-auto-scaling-service:v0.12.6
#        imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        volumeMounts:
        - name: cm-aass-volume
          mountPath: /opt/cloud/application-auto-scaling-service/conf
          readOnly: true
        - name: vol-log
          mountPath: /opt/cloud/logs/application-auto-scaling-service
          # policy字段是CCE自定义的字段，能够让ICAgent识别并采集日志
          policy:
            logs:
              rotate: ''
        env:
        - name: ak
          valueFrom:
            secretKeyRef:
              name: secret-aass
              key: ak
        - name: sk
          valueFrom:
            secretKeyRef:
              name: secret-aass
              key: sk
      volumes:
      - name: cm-aass-volume
        configMap:
          name: cm-aass
      - emptyDir: {}
        name: vol-1og